"""initial schema

Revision ID: cb62ff90211e
Revises: 
Create Date: 2026-10-09 03:00:33.602385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb62ff90211e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('avatar_color', sa.String(length=7), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_code', sa.String(length=11), nullable=True),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('meeting_type', sa.Enum('instant', 'scheduled', 'personal', name='meeting_type', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'live', 'ended', name='meeting_status', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('use_pmi', sa.Boolean(), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('passcode', sa.String(length=10), nullable=True),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('waiting_room', sa.Boolean(), nullable=False),
    sa.Column('mute_on_entry', sa.Boolean(), nullable=False),
    sa.Column('host_video', sa.Boolean(), nullable=False),
    sa.Column('participant_video', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("meeting_type != 'scheduled' OR (scheduled_start IS NOT NULL AND duration_minutes IS NOT NULL)", name='ck_meetings_scheduled_has_time'),
    sa.CheckConstraint('(use_pmi = 1 AND meeting_code IS NULL AND invite_token IS NULL) OR (use_pmi = 0 AND meeting_code IS NOT NULL AND invite_token IS NOT NULL)', name='ck_meetings_code_or_pmi'),
    sa.CheckConstraint('duration_minutes IS NULL OR duration_minutes > 0', name='ck_meetings_duration_positive'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meetings_host_id'), ['host_id'], unique=False)
        batch_op.create_index('ix_meetings_host_start', ['host_id', 'scheduled_start'], unique=False)
        batch_op.create_index(batch_op.f('ix_meetings_meeting_code'), ['meeting_code'], unique=True)
        batch_op.create_index('uq_meetings_one_personal_per_host', ['host_id'], unique=True, sqlite_where=sa.text("meeting_type = 'personal'"))

    op.create_table('user_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mute_mic_on_join', sa.Boolean(), nullable=False),
    sa.Column('video_off_on_join', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('meeting_invitees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'email', name='uq_invitee_per_meeting')
    )
    with op.batch_alter_table('meeting_invitees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_invitees_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_invitees_user_id'), ['user_id'], unique=False)

    op.create_table('meeting_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('host', 'co_host', 'attendee', name='participant_role', native_enum=False, create_constraint=True, length=20), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.Column('left_at', sa.DateTime(), nullable=True),
    sa.Column('was_removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_participants_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_participants_meeting_active', ['meeting_id', 'left_at'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_id'], ['meeting_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['meeting_participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index('ix_chat_meeting_sent', ['meeting_id', 'sent_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_chat_meeting_sent')

    op.drop_table('chat_messages')
    with op.batch_alter_table('meeting_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_participants_meeting_active')
        batch_op.drop_index(batch_op.f('ix_meeting_participants_user_id'))

    op.drop_table('meeting_participants')
    with op.batch_alter_table('meeting_invitees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_invitees_user_id'))
        batch_op.drop_index(batch_op.f('ix_meeting_invitees_meeting_id'))

    op.drop_table('meeting_invitees')
    op.drop_table('user_settings')
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_index('uq_meetings_one_personal_per_host', sqlite_where=sa.text("meeting_type = 'personal'"))
        batch_op.drop_index(batch_op.f('ix_meetings_meeting_code'))
        batch_op.drop_index('ix_meetings_host_start')
        batch_op.drop_index(batch_op.f('ix_meetings_host_id'))

    op.drop_table('meetings')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
